// Code generated by terraform-plugin-framework-generator DO NOT EDIT.

package resource_autopilotnodepool

import (
	"context"
	"fmt"
	"github.com/hashicorp/terraform-plugin-framework-validators/int64validator"
	"github.com/hashicorp/terraform-plugin-framework-validators/stringvalidator"
	"github.com/hashicorp/terraform-plugin-framework/attr"
	"github.com/hashicorp/terraform-plugin-framework/diag"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/int64planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/listplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/planmodifier"
	"github.com/hashicorp/terraform-plugin-framework/resource/schema/stringplanmodifier"
	"github.com/hashicorp/terraform-plugin-framework/schema/validator"
	"github.com/hashicorp/terraform-plugin-framework/types"
	"github.com/hashicorp/terraform-plugin-framework/types/basetypes"
	"github.com/hashicorp/terraform-plugin-go/tftypes"
	"regexp"
	"strings"

	"github.com/hashicorp/terraform-plugin-framework/resource/schema"
)

func AutopilotnodepoolResourceSchema(ctx context.Context) schema.Schema {
	return schema.Schema{
		Attributes: map[string]schema.Attribute{
			"allocation_strategy": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "How eligible server classes are ranked. Only LowestPrice is accepted.",
				MarkdownDescription: "How eligible server classes are ranked. Only LowestPrice is accepted.",
				Validators: []validator.String{
					stringvalidator.OneOf("LowestPrice"),
				},
			},
			"allocations": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"bid_price_per_hour": schema.StringAttribute{
							Computed:            true,
							Description:         "Bid price per hour (USD) placed for this class.",
							MarkdownDescription: "Bid price per hour (USD) placed for this class.",
						},
						"desired_nodes": schema.Int64Attribute{
							Computed:            true,
							Description:         "Desired node count for this allocation.",
							MarkdownDescription: "Desired node count for this allocation.",
						},
						"market_price_per_hour": schema.StringAttribute{
							Computed:            true,
							Description:         "Market clearing price per hour (USD) for this class.",
							MarkdownDescription: "Market clearing price per hour (USD) for this class.",
						},
						"memory_gb_per_node": schema.StringAttribute{
							Computed:            true,
							Description:         "Memory (GB) per node for this class.",
							MarkdownDescription: "Memory (GB) per node for this class.",
						},
						"server_class": schema.StringAttribute{
							Computed:            true,
							Description:         "The server class fulfilling this allocation.",
							MarkdownDescription: "The server class fulfilling this allocation.",
						},
						"spot_node_pool": schema.StringAttribute{
							Computed:            true,
							Description:         "Name of the child SpotNodePool fulfilling this allocation.",
							MarkdownDescription: "Name of the child SpotNodePool fulfilling this allocation.",
						},
						"vcpu_per_node": schema.Int64Attribute{
							Computed:            true,
							Description:         "vCPUs per node for this class.",
							MarkdownDescription: "vCPUs per node for this class.",
						},
						"won_nodes": schema.Int64Attribute{
							Computed:            true,
							Description:         "Won node count for this allocation.",
							MarkdownDescription: "Won node count for this allocation.",
						},
					},
					CustomType: AllocationsType{
						ObjectType: types.ObjectType{
							AttrTypes: AllocationsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Computed:            true,
				Description:         "Per-server-class allocation breakdown.",
				MarkdownDescription: "Per-server-class allocation breakdown.",
				PlanModifiers: []planmodifier.List{
					listplanmodifier.UseStateForUnknown(),
				},
			},
			"annotations": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Annotations to be applied to the nodes of the node pool",
				MarkdownDescription: "Annotations to be applied to the nodes of the node pool",
			},
			"budget_per_hour": schema.StringAttribute{
				Required:            true,
				Description:         "Hourly budget (USD), read as a bid ceiling. Positive, up to three decimal places.",
				MarkdownDescription: "Hourly budget (USD), read as a bid ceiling. Positive, up to three decimal places.",
				Validators: []validator.String{
					stringvalidator.RegexMatches(regexp.MustCompile(`^\d+(\.\d{1,3})?$`), "Must be a positive number with up to three decimal places"),
				},
			},
			"cloudspace_name": schema.StringAttribute{
				Required:            true,
				Description:         "The name of the cloudspace the resulting nodes join.",
				MarkdownDescription: "The name of the cloudspace the resulting nodes join.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
				},
				Validators: []validator.String{
					stringvalidator.LengthBetween(1, 63),
					stringvalidator.RegexMatches(regexp.MustCompile(`^[a-zA-Z0-9]([-a-zA-Z0-9]*[a-zA-Z0-9])?$`), "Must be valid kubernetes name"),
				},
			},
			"id": schema.StringAttribute{
				Computed:            true,
				Description:         "The id of the autopilotnodepool.",
				MarkdownDescription: "The id of the autopilotnodepool.",
				DeprecationMessage:  "Use the name attribute instead",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"labels": schema.MapAttribute{
				ElementType:         types.StringType,
				Optional:            true,
				Description:         "Labels to be applied to the nodes of the node pool",
				MarkdownDescription: "Labels to be applied to the nodes of the node pool",
			},
			"last_updated": schema.StringAttribute{
				Computed:            true,
				Description:         "The last time the autopilotnodepool was updated.",
				MarkdownDescription: "The last time the autopilotnodepool was updated.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managed_memory_gb": schema.StringAttribute{
				Computed:            true,
				Description:         "Total memory (GB) currently won across child pools.",
				MarkdownDescription: "Total memory (GB) currently won across child pools.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"managed_vcpus": schema.Int64Attribute{
				Computed:            true,
				Description:         "Total vCPUs currently won across child pools.",
				MarkdownDescription: "Total vCPUs currently won across child pools.",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"memory_per_vcpu": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Required memory-to-vCPU ratio in GB: any, 2, 4, or 8. Defaults to any.",
				MarkdownDescription: "Required memory-to-vCPU ratio in GB: any, 2, 4, or 8. Defaults to any.",
				Validators: []validator.String{
					stringvalidator.OneOf("any", "2", "4", "8"),
				},
			},
			"name": schema.StringAttribute{
				Computed:            true,
				Description:         "The name of the autopilotnodepool.",
				MarkdownDescription: "The name of the autopilotnodepool.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"phase": schema.StringAttribute{
				Computed:            true,
				Description:         "Fulfillment phase of the autopilot pool.",
				MarkdownDescription: "Fulfillment phase of the autopilot pool.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"region": schema.StringAttribute{
				Optional:            true,
				Computed:            true,
				Description:         "Region whose server classes are eligible for this autopilot pool. Defaults to the referenced cloudspace's region when omitted. Immutable.",
				MarkdownDescription: "Region whose server classes are eligible for this autopilot pool. Defaults to the referenced cloudspace's region when omitted. Immutable.",
				PlanModifiers: []planmodifier.String{
					stringplanmodifier.RequiresReplace(),
					stringplanmodifier.UseStateForUnknown(),
				},
			},
			"taints": schema.ListNestedAttribute{
				NestedObject: schema.NestedAttributeObject{
					Attributes: map[string]schema.Attribute{
						"effect": schema.StringAttribute{
							Required:            true,
							Description:         "The taint effect (NoSchedule, PreferNoSchedule, or NoExecute)",
							MarkdownDescription: "The taint effect (NoSchedule, PreferNoSchedule, or NoExecute)",
							Validators: []validator.String{
								stringvalidator.OneOf("NoSchedule", "PreferNoSchedule", "NoExecute"),
							},
						},
						"key": schema.StringAttribute{
							Required:            true,
							Description:         "The taint key to be applied",
							MarkdownDescription: "The taint key to be applied",
						},
						"value": schema.StringAttribute{
							Optional:            true,
							Description:         "The taint value",
							MarkdownDescription: "The taint value",
						},
					},
					CustomType: TaintsType{
						ObjectType: types.ObjectType{
							AttrTypes: TaintsValue{}.AttributeTypes(ctx),
						},
					},
				},
				Optional:            true,
				Description:         "Kubernetes taints to be applied to the nodes of the node pool",
				MarkdownDescription: "Kubernetes taints to be applied to the nodes of the node pool",
			},
			"target_vcpus": schema.Int64Attribute{
				Computed:            true,
				Description:         "vCPU count Spot is filling (== vcpu.total).",
				MarkdownDescription: "vCPU count Spot is filling (== vcpu.total).",
				PlanModifiers: []planmodifier.Int64{
					int64planmodifier.UseStateForUnknown(),
				},
			},
			"vcpu": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"total": schema.Int64Attribute{
						Required:            true,
						Description:         "Total vCPUs to fill (a positive multiple of the smallest usable node).",
						MarkdownDescription: "Total vCPUs to fill (a positive multiple of the smallest usable node).",
						Validators: []validator.Int64{
							int64validator.AtLeast(1),
						},
					},
				},
				CustomType: VcpuType{
					ObjectType: types.ObjectType{
						AttrTypes: VcpuValue{}.AttributeTypes(ctx),
					},
				},
				Required:            true,
				Description:         "Total vCPU target Spot fills exactly via a combination pack.",
				MarkdownDescription: "Total vCPU target Spot fills exactly via a combination pack.",
			},
			"vcpu_per_node": schema.SingleNestedAttribute{
				Attributes: map[string]schema.Attribute{
					"max": schema.Int64Attribute{
						Optional:            true,
						Description:         "Maximum vCPUs per node.",
						MarkdownDescription: "Maximum vCPUs per node.",
						Validators: []validator.Int64{
							int64validator.AtLeast(1),
						},
					},
					"min": schema.Int64Attribute{
						Optional:            true,
						Description:         "Minimum vCPUs per node.",
						MarkdownDescription: "Minimum vCPUs per node.",
						Validators: []validator.Int64{
							int64validator.AtLeast(1),
						},
					},
				},
				CustomType: VcpuPerNodeType{
					ObjectType: types.ObjectType{
						AttrTypes: VcpuPerNodeValue{}.AttributeTypes(ctx),
					},
				},
				Optional:            true,
				Description:         "Optionally bounds the size of each individual node/server.",
				MarkdownDescription: "Optionally bounds the size of each individual node/server.",
			},
		},
	}
}

type AutopilotnodepoolModel struct {
	AllocationStrategy types.String     `tfsdk:"allocation_strategy"`
	Allocations        types.List       `tfsdk:"allocations"`
	Annotations        types.Map        `tfsdk:"annotations"`
	BudgetPerHour      types.String     `tfsdk:"budget_per_hour"`
	CloudspaceName     types.String     `tfsdk:"cloudspace_name"`
	Id                 types.String     `tfsdk:"id"`
	Labels             types.Map        `tfsdk:"labels"`
	LastUpdated        types.String     `tfsdk:"last_updated"`
	ManagedMemoryGb    types.String     `tfsdk:"managed_memory_gb"`
	ManagedVcpus       types.Int64      `tfsdk:"managed_vcpus"`
	MemoryPerVcpu      types.String     `tfsdk:"memory_per_vcpu"`
	Name               types.String     `tfsdk:"name"`
	Phase              types.String     `tfsdk:"phase"`
	Region             types.String     `tfsdk:"region"`
	Taints             types.List       `tfsdk:"taints"`
	TargetVcpus        types.Int64      `tfsdk:"target_vcpus"`
	Vcpu               VcpuValue        `tfsdk:"vcpu"`
	VcpuPerNode        VcpuPerNodeValue `tfsdk:"vcpu_per_node"`
}

var _ basetypes.ObjectTypable = AllocationsType{}

type AllocationsType struct {
	basetypes.ObjectType
}

func (t AllocationsType) Equal(o attr.Type) bool {
	other, ok := o.(AllocationsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t AllocationsType) String() string {
	return "AllocationsType"
}

func (t AllocationsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	bidPricePerHourAttribute, ok := attributes["bid_price_per_hour"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`bid_price_per_hour is missing from object`)

		return nil, diags
	}

	bidPricePerHourVal, ok := bidPricePerHourAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`bid_price_per_hour expected to be basetypes.StringValue, was: %T`, bidPricePerHourAttribute))
	}

	desiredNodesAttribute, ok := attributes["desired_nodes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`desired_nodes is missing from object`)

		return nil, diags
	}

	desiredNodesVal, ok := desiredNodesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`desired_nodes expected to be basetypes.Int64Value, was: %T`, desiredNodesAttribute))
	}

	marketPricePerHourAttribute, ok := attributes["market_price_per_hour"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`market_price_per_hour is missing from object`)

		return nil, diags
	}

	marketPricePerHourVal, ok := marketPricePerHourAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`market_price_per_hour expected to be basetypes.StringValue, was: %T`, marketPricePerHourAttribute))
	}

	memoryGbPerNodeAttribute, ok := attributes["memory_gb_per_node"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`memory_gb_per_node is missing from object`)

		return nil, diags
	}

	memoryGbPerNodeVal, ok := memoryGbPerNodeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`memory_gb_per_node expected to be basetypes.StringValue, was: %T`, memoryGbPerNodeAttribute))
	}

	serverClassAttribute, ok := attributes["server_class"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server_class is missing from object`)

		return nil, diags
	}

	serverClassVal, ok := serverClassAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server_class expected to be basetypes.StringValue, was: %T`, serverClassAttribute))
	}

	spotNodePoolAttribute, ok := attributes["spot_node_pool"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`spot_node_pool is missing from object`)

		return nil, diags
	}

	spotNodePoolVal, ok := spotNodePoolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`spot_node_pool expected to be basetypes.StringValue, was: %T`, spotNodePoolAttribute))
	}

	vcpuPerNodeAttribute, ok := attributes["vcpu_per_node"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vcpu_per_node is missing from object`)

		return nil, diags
	}

	vcpuPerNodeVal, ok := vcpuPerNodeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vcpu_per_node expected to be basetypes.Int64Value, was: %T`, vcpuPerNodeAttribute))
	}

	wonNodesAttribute, ok := attributes["won_nodes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`won_nodes is missing from object`)

		return nil, diags
	}

	wonNodesVal, ok := wonNodesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`won_nodes expected to be basetypes.Int64Value, was: %T`, wonNodesAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return AllocationsValue{
		BidPricePerHour:    bidPricePerHourVal,
		DesiredNodes:       desiredNodesVal,
		MarketPricePerHour: marketPricePerHourVal,
		MemoryGbPerNode:    memoryGbPerNodeVal,
		ServerClass:        serverClassVal,
		SpotNodePool:       spotNodePoolVal,
		VcpuPerNode:        vcpuPerNodeVal,
		WonNodes:           wonNodesVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewAllocationsValueNull() AllocationsValue {
	return AllocationsValue{
		state: attr.ValueStateNull,
	}
}

func NewAllocationsValueUnknown() AllocationsValue {
	return AllocationsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewAllocationsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (AllocationsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing AllocationsValue Attribute Value",
				"While creating a AllocationsValue value, a missing attribute value was detected. "+
					"A AllocationsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AllocationsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid AllocationsValue Attribute Type",
				"While creating a AllocationsValue value, an invalid attribute value was detected. "+
					"A AllocationsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("AllocationsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("AllocationsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra AllocationsValue Attribute Value",
				"While creating a AllocationsValue value, an extra attribute value was detected. "+
					"A AllocationsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra AllocationsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewAllocationsValueUnknown(), diags
	}

	bidPricePerHourAttribute, ok := attributes["bid_price_per_hour"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`bid_price_per_hour is missing from object`)

		return NewAllocationsValueUnknown(), diags
	}

	bidPricePerHourVal, ok := bidPricePerHourAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`bid_price_per_hour expected to be basetypes.StringValue, was: %T`, bidPricePerHourAttribute))
	}

	desiredNodesAttribute, ok := attributes["desired_nodes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`desired_nodes is missing from object`)

		return NewAllocationsValueUnknown(), diags
	}

	desiredNodesVal, ok := desiredNodesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`desired_nodes expected to be basetypes.Int64Value, was: %T`, desiredNodesAttribute))
	}

	marketPricePerHourAttribute, ok := attributes["market_price_per_hour"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`market_price_per_hour is missing from object`)

		return NewAllocationsValueUnknown(), diags
	}

	marketPricePerHourVal, ok := marketPricePerHourAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`market_price_per_hour expected to be basetypes.StringValue, was: %T`, marketPricePerHourAttribute))
	}

	memoryGbPerNodeAttribute, ok := attributes["memory_gb_per_node"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`memory_gb_per_node is missing from object`)

		return NewAllocationsValueUnknown(), diags
	}

	memoryGbPerNodeVal, ok := memoryGbPerNodeAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`memory_gb_per_node expected to be basetypes.StringValue, was: %T`, memoryGbPerNodeAttribute))
	}

	serverClassAttribute, ok := attributes["server_class"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`server_class is missing from object`)

		return NewAllocationsValueUnknown(), diags
	}

	serverClassVal, ok := serverClassAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`server_class expected to be basetypes.StringValue, was: %T`, serverClassAttribute))
	}

	spotNodePoolAttribute, ok := attributes["spot_node_pool"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`spot_node_pool is missing from object`)

		return NewAllocationsValueUnknown(), diags
	}

	spotNodePoolVal, ok := spotNodePoolAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`spot_node_pool expected to be basetypes.StringValue, was: %T`, spotNodePoolAttribute))
	}

	vcpuPerNodeAttribute, ok := attributes["vcpu_per_node"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`vcpu_per_node is missing from object`)

		return NewAllocationsValueUnknown(), diags
	}

	vcpuPerNodeVal, ok := vcpuPerNodeAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`vcpu_per_node expected to be basetypes.Int64Value, was: %T`, vcpuPerNodeAttribute))
	}

	wonNodesAttribute, ok := attributes["won_nodes"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`won_nodes is missing from object`)

		return NewAllocationsValueUnknown(), diags
	}

	wonNodesVal, ok := wonNodesAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`won_nodes expected to be basetypes.Int64Value, was: %T`, wonNodesAttribute))
	}

	if diags.HasError() {
		return NewAllocationsValueUnknown(), diags
	}

	return AllocationsValue{
		BidPricePerHour:    bidPricePerHourVal,
		DesiredNodes:       desiredNodesVal,
		MarketPricePerHour: marketPricePerHourVal,
		MemoryGbPerNode:    memoryGbPerNodeVal,
		ServerClass:        serverClassVal,
		SpotNodePool:       spotNodePoolVal,
		VcpuPerNode:        vcpuPerNodeVal,
		WonNodes:           wonNodesVal,
		state:              attr.ValueStateKnown,
	}, diags
}

func NewAllocationsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) AllocationsValue {
	object, diags := NewAllocationsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewAllocationsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t AllocationsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewAllocationsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewAllocationsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewAllocationsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewAllocationsValueMust(AllocationsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t AllocationsType) ValueType(ctx context.Context) attr.Value {
	return AllocationsValue{}
}

var _ basetypes.ObjectValuable = AllocationsValue{}

type AllocationsValue struct {
	BidPricePerHour    basetypes.StringValue `tfsdk:"bid_price_per_hour"`
	DesiredNodes       basetypes.Int64Value  `tfsdk:"desired_nodes"`
	MarketPricePerHour basetypes.StringValue `tfsdk:"market_price_per_hour"`
	MemoryGbPerNode    basetypes.StringValue `tfsdk:"memory_gb_per_node"`
	ServerClass        basetypes.StringValue `tfsdk:"server_class"`
	SpotNodePool       basetypes.StringValue `tfsdk:"spot_node_pool"`
	VcpuPerNode        basetypes.Int64Value  `tfsdk:"vcpu_per_node"`
	WonNodes           basetypes.Int64Value  `tfsdk:"won_nodes"`
	state              attr.ValueState
}

func (v AllocationsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 8)

	var val tftypes.Value
	var err error

	attrTypes["bid_price_per_hour"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["desired_nodes"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["market_price_per_hour"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["memory_gb_per_node"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["server_class"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["spot_node_pool"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["vcpu_per_node"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["won_nodes"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 8)

		val, err = v.BidPricePerHour.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["bid_price_per_hour"] = val

		val, err = v.DesiredNodes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["desired_nodes"] = val

		val, err = v.MarketPricePerHour.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["market_price_per_hour"] = val

		val, err = v.MemoryGbPerNode.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["memory_gb_per_node"] = val

		val, err = v.ServerClass.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["server_class"] = val

		val, err = v.SpotNodePool.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["spot_node_pool"] = val

		val, err = v.VcpuPerNode.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["vcpu_per_node"] = val

		val, err = v.WonNodes.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["won_nodes"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v AllocationsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v AllocationsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v AllocationsValue) String() string {
	return "AllocationsValue"
}

func (v AllocationsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"bid_price_per_hour":    basetypes.StringType{},
			"desired_nodes":         basetypes.Int64Type{},
			"market_price_per_hour": basetypes.StringType{},
			"memory_gb_per_node":    basetypes.StringType{},
			"server_class":          basetypes.StringType{},
			"spot_node_pool":        basetypes.StringType{},
			"vcpu_per_node":         basetypes.Int64Type{},
			"won_nodes":             basetypes.Int64Type{},
		},
		map[string]attr.Value{
			"bid_price_per_hour":    v.BidPricePerHour,
			"desired_nodes":         v.DesiredNodes,
			"market_price_per_hour": v.MarketPricePerHour,
			"memory_gb_per_node":    v.MemoryGbPerNode,
			"server_class":          v.ServerClass,
			"spot_node_pool":        v.SpotNodePool,
			"vcpu_per_node":         v.VcpuPerNode,
			"won_nodes":             v.WonNodes,
		})

	return objVal, diags
}

func (v AllocationsValue) Equal(o attr.Value) bool {
	other, ok := o.(AllocationsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.BidPricePerHour.Equal(other.BidPricePerHour) {
		return false
	}

	if !v.DesiredNodes.Equal(other.DesiredNodes) {
		return false
	}

	if !v.MarketPricePerHour.Equal(other.MarketPricePerHour) {
		return false
	}

	if !v.MemoryGbPerNode.Equal(other.MemoryGbPerNode) {
		return false
	}

	if !v.ServerClass.Equal(other.ServerClass) {
		return false
	}

	if !v.SpotNodePool.Equal(other.SpotNodePool) {
		return false
	}

	if !v.VcpuPerNode.Equal(other.VcpuPerNode) {
		return false
	}

	if !v.WonNodes.Equal(other.WonNodes) {
		return false
	}

	return true
}

func (v AllocationsValue) Type(ctx context.Context) attr.Type {
	return AllocationsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v AllocationsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"bid_price_per_hour":    basetypes.StringType{},
		"desired_nodes":         basetypes.Int64Type{},
		"market_price_per_hour": basetypes.StringType{},
		"memory_gb_per_node":    basetypes.StringType{},
		"server_class":          basetypes.StringType{},
		"spot_node_pool":        basetypes.StringType{},
		"vcpu_per_node":         basetypes.Int64Type{},
		"won_nodes":             basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = TaintsType{}

type TaintsType struct {
	basetypes.ObjectType
}

func (t TaintsType) Equal(o attr.Type) bool {
	other, ok := o.(TaintsType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t TaintsType) String() string {
	return "TaintsType"
}

func (t TaintsType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	effectAttribute, ok := attributes["effect"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`effect is missing from object`)

		return nil, diags
	}

	effectVal, ok := effectAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`effect expected to be basetypes.StringValue, was: %T`, effectAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return nil, diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return nil, diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return TaintsValue{
		Effect: effectVal,
		Key:    keyVal,
		Value:  valueVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTaintsValueNull() TaintsValue {
	return TaintsValue{
		state: attr.ValueStateNull,
	}
}

func NewTaintsValueUnknown() TaintsValue {
	return TaintsValue{
		state: attr.ValueStateUnknown,
	}
}

func NewTaintsValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (TaintsValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing TaintsValue Attribute Value",
				"While creating a TaintsValue value, a missing attribute value was detected. "+
					"A TaintsValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TaintsValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid TaintsValue Attribute Type",
				"While creating a TaintsValue value, an invalid attribute value was detected. "+
					"A TaintsValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("TaintsValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("TaintsValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra TaintsValue Attribute Value",
				"While creating a TaintsValue value, an extra attribute value was detected. "+
					"A TaintsValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra TaintsValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewTaintsValueUnknown(), diags
	}

	effectAttribute, ok := attributes["effect"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`effect is missing from object`)

		return NewTaintsValueUnknown(), diags
	}

	effectVal, ok := effectAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`effect expected to be basetypes.StringValue, was: %T`, effectAttribute))
	}

	keyAttribute, ok := attributes["key"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`key is missing from object`)

		return NewTaintsValueUnknown(), diags
	}

	keyVal, ok := keyAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`key expected to be basetypes.StringValue, was: %T`, keyAttribute))
	}

	valueAttribute, ok := attributes["value"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`value is missing from object`)

		return NewTaintsValueUnknown(), diags
	}

	valueVal, ok := valueAttribute.(basetypes.StringValue)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`value expected to be basetypes.StringValue, was: %T`, valueAttribute))
	}

	if diags.HasError() {
		return NewTaintsValueUnknown(), diags
	}

	return TaintsValue{
		Effect: effectVal,
		Key:    keyVal,
		Value:  valueVal,
		state:  attr.ValueStateKnown,
	}, diags
}

func NewTaintsValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) TaintsValue {
	object, diags := NewTaintsValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewTaintsValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t TaintsType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewTaintsValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewTaintsValueUnknown(), nil
	}

	if in.IsNull() {
		return NewTaintsValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewTaintsValueMust(TaintsValue{}.AttributeTypes(ctx), attributes), nil
}

func (t TaintsType) ValueType(ctx context.Context) attr.Value {
	return TaintsValue{}
}

var _ basetypes.ObjectValuable = TaintsValue{}

type TaintsValue struct {
	Effect basetypes.StringValue `tfsdk:"effect"`
	Key    basetypes.StringValue `tfsdk:"key"`
	Value  basetypes.StringValue `tfsdk:"value"`
	state  attr.ValueState
}

func (v TaintsValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 3)

	var val tftypes.Value
	var err error

	attrTypes["effect"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["key"] = basetypes.StringType{}.TerraformType(ctx)
	attrTypes["value"] = basetypes.StringType{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 3)

		val, err = v.Effect.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["effect"] = val

		val, err = v.Key.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["key"] = val

		val, err = v.Value.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["value"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v TaintsValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v TaintsValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v TaintsValue) String() string {
	return "TaintsValue"
}

func (v TaintsValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"effect": basetypes.StringType{},
			"key":    basetypes.StringType{},
			"value":  basetypes.StringType{},
		},
		map[string]attr.Value{
			"effect": v.Effect,
			"key":    v.Key,
			"value":  v.Value,
		})

	return objVal, diags
}

func (v TaintsValue) Equal(o attr.Value) bool {
	other, ok := o.(TaintsValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Effect.Equal(other.Effect) {
		return false
	}

	if !v.Key.Equal(other.Key) {
		return false
	}

	if !v.Value.Equal(other.Value) {
		return false
	}

	return true
}

func (v TaintsValue) Type(ctx context.Context) attr.Type {
	return TaintsType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v TaintsValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"effect": basetypes.StringType{},
		"key":    basetypes.StringType{},
		"value":  basetypes.StringType{},
	}
}

var _ basetypes.ObjectTypable = VcpuType{}

type VcpuType struct {
	basetypes.ObjectType
}

func (t VcpuType) Equal(o attr.Type) bool {
	other, ok := o.(VcpuType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t VcpuType) String() string {
	return "VcpuType"
}

func (t VcpuType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	totalAttribute, ok := attributes["total"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total is missing from object`)

		return nil, diags
	}

	totalVal, ok := totalAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total expected to be basetypes.Int64Value, was: %T`, totalAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return VcpuValue{
		Total: totalVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewVcpuValueNull() VcpuValue {
	return VcpuValue{
		state: attr.ValueStateNull,
	}
}

func NewVcpuValueUnknown() VcpuValue {
	return VcpuValue{
		state: attr.ValueStateUnknown,
	}
}

func NewVcpuValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (VcpuValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing VcpuValue Attribute Value",
				"While creating a VcpuValue value, a missing attribute value was detected. "+
					"A VcpuValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VcpuValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid VcpuValue Attribute Type",
				"While creating a VcpuValue value, an invalid attribute value was detected. "+
					"A VcpuValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VcpuValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("VcpuValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra VcpuValue Attribute Value",
				"While creating a VcpuValue value, an extra attribute value was detected. "+
					"A VcpuValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra VcpuValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewVcpuValueUnknown(), diags
	}

	totalAttribute, ok := attributes["total"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`total is missing from object`)

		return NewVcpuValueUnknown(), diags
	}

	totalVal, ok := totalAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`total expected to be basetypes.Int64Value, was: %T`, totalAttribute))
	}

	if diags.HasError() {
		return NewVcpuValueUnknown(), diags
	}

	return VcpuValue{
		Total: totalVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewVcpuValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) VcpuValue {
	object, diags := NewVcpuValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewVcpuValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t VcpuType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewVcpuValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewVcpuValueUnknown(), nil
	}

	if in.IsNull() {
		return NewVcpuValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewVcpuValueMust(VcpuValue{}.AttributeTypes(ctx), attributes), nil
}

func (t VcpuType) ValueType(ctx context.Context) attr.Value {
	return VcpuValue{}
}

var _ basetypes.ObjectValuable = VcpuValue{}

type VcpuValue struct {
	Total basetypes.Int64Value `tfsdk:"total"`
	state attr.ValueState
}

func (v VcpuValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 1)

	var val tftypes.Value
	var err error

	attrTypes["total"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 1)

		val, err = v.Total.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["total"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v VcpuValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v VcpuValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v VcpuValue) String() string {
	return "VcpuValue"
}

func (v VcpuValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"total": basetypes.Int64Type{},
		},
		map[string]attr.Value{
			"total": v.Total,
		})

	return objVal, diags
}

func (v VcpuValue) Equal(o attr.Value) bool {
	other, ok := o.(VcpuValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Total.Equal(other.Total) {
		return false
	}

	return true
}

func (v VcpuValue) Type(ctx context.Context) attr.Type {
	return VcpuType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v VcpuValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"total": basetypes.Int64Type{},
	}
}

var _ basetypes.ObjectTypable = VcpuPerNodeType{}

type VcpuPerNodeType struct {
	basetypes.ObjectType
}

func (t VcpuPerNodeType) Equal(o attr.Type) bool {
	other, ok := o.(VcpuPerNodeType)

	if !ok {
		return false
	}

	return t.ObjectType.Equal(other.ObjectType)
}

func (t VcpuPerNodeType) String() string {
	return "VcpuPerNodeType"
}

func (t VcpuPerNodeType) ValueFromObject(ctx context.Context, in basetypes.ObjectValue) (basetypes.ObjectValuable, diag.Diagnostics) {
	var diags diag.Diagnostics

	attributes := in.Attributes()

	maxAttribute, ok := attributes["max"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max is missing from object`)

		return nil, diags
	}

	maxVal, ok := maxAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max expected to be basetypes.Int64Value, was: %T`, maxAttribute))
	}

	minAttribute, ok := attributes["min"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`min is missing from object`)

		return nil, diags
	}

	minVal, ok := minAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`min expected to be basetypes.Int64Value, was: %T`, minAttribute))
	}

	if diags.HasError() {
		return nil, diags
	}

	return VcpuPerNodeValue{
		Max:   maxVal,
		Min:   minVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewVcpuPerNodeValueNull() VcpuPerNodeValue {
	return VcpuPerNodeValue{
		state: attr.ValueStateNull,
	}
}

func NewVcpuPerNodeValueUnknown() VcpuPerNodeValue {
	return VcpuPerNodeValue{
		state: attr.ValueStateUnknown,
	}
}

func NewVcpuPerNodeValue(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) (VcpuPerNodeValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	// Reference: https://github.com/hashicorp/terraform-plugin-framework/issues/521
	ctx := context.Background()

	for name, attributeType := range attributeTypes {
		attribute, ok := attributes[name]

		if !ok {
			diags.AddError(
				"Missing VcpuPerNodeValue Attribute Value",
				"While creating a VcpuPerNodeValue value, a missing attribute value was detected. "+
					"A VcpuPerNodeValue must contain values for all attributes, even if null or unknown. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VcpuPerNodeValue Attribute Name (%s) Expected Type: %s", name, attributeType.String()),
			)

			continue
		}

		if !attributeType.Equal(attribute.Type(ctx)) {
			diags.AddError(
				"Invalid VcpuPerNodeValue Attribute Type",
				"While creating a VcpuPerNodeValue value, an invalid attribute value was detected. "+
					"A VcpuPerNodeValue must use a matching attribute type for the value. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("VcpuPerNodeValue Attribute Name (%s) Expected Type: %s\n", name, attributeType.String())+
					fmt.Sprintf("VcpuPerNodeValue Attribute Name (%s) Given Type: %s", name, attribute.Type(ctx)),
			)
		}
	}

	for name := range attributes {
		_, ok := attributeTypes[name]

		if !ok {
			diags.AddError(
				"Extra VcpuPerNodeValue Attribute Value",
				"While creating a VcpuPerNodeValue value, an extra attribute value was detected. "+
					"A VcpuPerNodeValue must not contain values beyond the expected attribute types. "+
					"This is always an issue with the provider and should be reported to the provider developers.\n\n"+
					fmt.Sprintf("Extra VcpuPerNodeValue Attribute Name: %s", name),
			)
		}
	}

	if diags.HasError() {
		return NewVcpuPerNodeValueUnknown(), diags
	}

	maxAttribute, ok := attributes["max"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`max is missing from object`)

		return NewVcpuPerNodeValueUnknown(), diags
	}

	maxVal, ok := maxAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`max expected to be basetypes.Int64Value, was: %T`, maxAttribute))
	}

	minAttribute, ok := attributes["min"]

	if !ok {
		diags.AddError(
			"Attribute Missing",
			`min is missing from object`)

		return NewVcpuPerNodeValueUnknown(), diags
	}

	minVal, ok := minAttribute.(basetypes.Int64Value)

	if !ok {
		diags.AddError(
			"Attribute Wrong Type",
			fmt.Sprintf(`min expected to be basetypes.Int64Value, was: %T`, minAttribute))
	}

	if diags.HasError() {
		return NewVcpuPerNodeValueUnknown(), diags
	}

	return VcpuPerNodeValue{
		Max:   maxVal,
		Min:   minVal,
		state: attr.ValueStateKnown,
	}, diags
}

func NewVcpuPerNodeValueMust(attributeTypes map[string]attr.Type, attributes map[string]attr.Value) VcpuPerNodeValue {
	object, diags := NewVcpuPerNodeValue(attributeTypes, attributes)

	if diags.HasError() {
		// This could potentially be added to the diag package.
		diagsStrings := make([]string, 0, len(diags))

		for _, diagnostic := range diags {
			diagsStrings = append(diagsStrings, fmt.Sprintf(
				"%s | %s | %s",
				diagnostic.Severity(),
				diagnostic.Summary(),
				diagnostic.Detail()))
		}

		panic("NewVcpuPerNodeValueMust received error(s): " + strings.Join(diagsStrings, "\n"))
	}

	return object
}

func (t VcpuPerNodeType) ValueFromTerraform(ctx context.Context, in tftypes.Value) (attr.Value, error) {
	if in.Type() == nil {
		return NewVcpuPerNodeValueNull(), nil
	}

	if !in.Type().Equal(t.TerraformType(ctx)) {
		return nil, fmt.Errorf("expected %s, got %s", t.TerraformType(ctx), in.Type())
	}

	if !in.IsKnown() {
		return NewVcpuPerNodeValueUnknown(), nil
	}

	if in.IsNull() {
		return NewVcpuPerNodeValueNull(), nil
	}

	attributes := map[string]attr.Value{}

	val := map[string]tftypes.Value{}

	err := in.As(&val)

	if err != nil {
		return nil, err
	}

	for k, v := range val {
		a, err := t.AttrTypes[k].ValueFromTerraform(ctx, v)

		if err != nil {
			return nil, err
		}

		attributes[k] = a
	}

	return NewVcpuPerNodeValueMust(VcpuPerNodeValue{}.AttributeTypes(ctx), attributes), nil
}

func (t VcpuPerNodeType) ValueType(ctx context.Context) attr.Value {
	return VcpuPerNodeValue{}
}

var _ basetypes.ObjectValuable = VcpuPerNodeValue{}

type VcpuPerNodeValue struct {
	Max   basetypes.Int64Value `tfsdk:"max"`
	Min   basetypes.Int64Value `tfsdk:"min"`
	state attr.ValueState
}

func (v VcpuPerNodeValue) ToTerraformValue(ctx context.Context) (tftypes.Value, error) {
	attrTypes := make(map[string]tftypes.Type, 2)

	var val tftypes.Value
	var err error

	attrTypes["max"] = basetypes.Int64Type{}.TerraformType(ctx)
	attrTypes["min"] = basetypes.Int64Type{}.TerraformType(ctx)

	objectType := tftypes.Object{AttributeTypes: attrTypes}

	switch v.state {
	case attr.ValueStateKnown:
		vals := make(map[string]tftypes.Value, 2)

		val, err = v.Max.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["max"] = val

		val, err = v.Min.ToTerraformValue(ctx)

		if err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		vals["min"] = val

		if err := tftypes.ValidateValue(objectType, vals); err != nil {
			return tftypes.NewValue(objectType, tftypes.UnknownValue), err
		}

		return tftypes.NewValue(objectType, vals), nil
	case attr.ValueStateNull:
		return tftypes.NewValue(objectType, nil), nil
	case attr.ValueStateUnknown:
		return tftypes.NewValue(objectType, tftypes.UnknownValue), nil
	default:
		panic(fmt.Sprintf("unhandled Object state in ToTerraformValue: %s", v.state))
	}
}

func (v VcpuPerNodeValue) IsNull() bool {
	return v.state == attr.ValueStateNull
}

func (v VcpuPerNodeValue) IsUnknown() bool {
	return v.state == attr.ValueStateUnknown
}

func (v VcpuPerNodeValue) String() string {
	return "VcpuPerNodeValue"
}

func (v VcpuPerNodeValue) ToObjectValue(ctx context.Context) (basetypes.ObjectValue, diag.Diagnostics) {
	var diags diag.Diagnostics

	objVal, diags := types.ObjectValue(
		map[string]attr.Type{
			"max": basetypes.Int64Type{},
			"min": basetypes.Int64Type{},
		},
		map[string]attr.Value{
			"max": v.Max,
			"min": v.Min,
		})

	return objVal, diags
}

func (v VcpuPerNodeValue) Equal(o attr.Value) bool {
	other, ok := o.(VcpuPerNodeValue)

	if !ok {
		return false
	}

	if v.state != other.state {
		return false
	}

	if v.state != attr.ValueStateKnown {
		return true
	}

	if !v.Max.Equal(other.Max) {
		return false
	}

	if !v.Min.Equal(other.Min) {
		return false
	}

	return true
}

func (v VcpuPerNodeValue) Type(ctx context.Context) attr.Type {
	return VcpuPerNodeType{
		basetypes.ObjectType{
			AttrTypes: v.AttributeTypes(ctx),
		},
	}
}

func (v VcpuPerNodeValue) AttributeTypes(ctx context.Context) map[string]attr.Type {
	return map[string]attr.Type{
		"max": basetypes.Int64Type{},
		"min": basetypes.Int64Type{},
	}
}
